server:
  port: 9080

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: main
          clone-on-start: true
          force-pull: true
          delete-untracked-branches: true
